"""initial schema

Revision ID: 8fcca70cbcb1
Revises: 
Create Date: 2026-09-15 21:16:03.832712
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8fcca70cbcb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('section', name=op.f('pk_app_settings'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models'))
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('logic', sa.String(length=5), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sim_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n_patients', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_runs'))
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_tools', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('always', sa.Boolean(), nullable=False),
    sa.Column('use_in', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('tool_configs',
    sa.Column('tool_id', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tool_id', name=op.f('pk_tool_configs'))
    )
    op.create_table('action_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.String(length=10), nullable=False),
    sa.Column('bed', sa.String(length=10), nullable=False),
    sa.Column('intervention', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], name=op.f('fk_action_proposals_run_id_simulation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_proposals'))
    )
    op.create_index(op.f('ix_action_proposals_run_id'), 'action_proposals', ['run_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_session_id'), 'action_proposals', ['session_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_status'), 'action_proposals', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('pid', sa.String(length=10), nullable=False),
    sa.Column('bed', sa.String(length=10), nullable=False),
    sa.Column('tool_id', sa.String(length=80), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sim_first', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sim_last', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rounds_seen', sa.Integer(), nullable=False),
    sa.Column('missed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], name=op.f('fk_alerts_run_id_simulation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_key'), 'alerts', ['key'], unique=False)
    op.create_index(op.f('ix_alerts_run_id'), 'alerts', ['run_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.String(length=10), nullable=False),
    sa.Column('mrn', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('asa', sa.Integer(), nullable=False),
    sa.Column('surgery', sa.String(length=60), nullable=False),
    sa.Column('specialty', sa.String(length=40), nullable=False),
    sa.Column('anes_code', sa.String(length=10), nullable=False),
    sa.Column('anes_label', sa.String(length=40), nullable=False),
    sa.Column('comorbidities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allergies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('bed', sa.String(length=10), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pacu_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], name=op.f('fk_patients_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('run_id', 'pid', name=op.f('uq_patients_run_id'))
    )
    op.create_index(op.f('ix_patients_run_id'), 'patients', ['run_id'], unique=False)
    op.create_table('round_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sim_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('patients_checked', sa.Integer(), nullable=False),
    sa.Column('tools_run', sa.Integer(), nullable=False),
    sa.Column('n_critical', sa.Integer(), nullable=False),
    sa.Column('n_warning', sa.Integer(), nullable=False),
    sa.Column('n_info', sa.Integer(), nullable=False),
    sa.Column('new_alerts', sa.Integer(), nullable=False),
    sa.Column('resolved_alerts', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('patients', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=False),
    sa.Column('summary_source', sa.String(length=10), nullable=False),
    sa.Column('summary_status', sa.String(length=10), nullable=False),
    sa.Column('summary_error', sa.Text(), nullable=True),
    sa.Column('summary_model', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], name=op.f('fk_round_reports_run_id_simulation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_round_reports'))
    )
    op.create_index(op.f('ix_round_reports_run_id'), 'round_reports', ['run_id'], unique=False)
    op.create_index(op.f('ix_round_reports_started_at'), 'round_reports', ['started_at'], unique=False)
    op.create_table('clinical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('event_uid', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('injected', sa.Boolean(), nullable=False),
    sa.Column('peak', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treatments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_events_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_events'))
    )
    op.create_index(op.f('ix_clinical_events_patient_id'), 'clinical_events', ['patient_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('performed_by', sa.String(length=40), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('affected', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_interventions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    op.create_index(op.f('ix_interventions_patient_id'), 'interventions', ['patient_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drawn_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('paco2', sa.Float(), nullable=True),
    sa.Column('pao2', sa.Float(), nullable=True),
    sa.Column('hco3', sa.Float(), nullable=True),
    sa.Column('be', sa.Float(), nullable=True),
    sa.Column('hb', sa.Float(), nullable=True),
    sa.Column('k', sa.Float(), nullable=True),
    sa.Column('na', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('lactate', sa.Float(), nullable=True),
    sa.Column('ica', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_lab_results_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_results'))
    )
    op.create_index('ix_lab_results_patient_time', 'lab_results', ['patient_id', 'drawn_at'], unique=False)
    op.create_table('patient_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_notes_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_notes'))
    )
    op.create_index(op.f('ix_patient_notes_patient_id'), 'patient_notes', ['patient_id'], unique=False)
    op.create_table('vital_signs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('bed', sa.String(length=10), nullable=False),
    sa.Column('phase', sa.String(length=12), nullable=False),
    sa.Column('hr', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('map', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('etco2', sa.Float(), nullable=True),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('bis', sa.Float(), nullable=True),
    sa.Column('ppeak', sa.Float(), nullable=True),
    sa.Column('pain', sa.Float(), nullable=True),
    sa.Column('ebl_ml', sa.Float(), nullable=True),
    sa.Column('urine_ml', sa.Float(), nullable=True),
    sa.Column('fluids_ml', sa.Float(), nullable=True),
    sa.Column('case_min', sa.Float(), nullable=True),
    sa.Column('event_level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_vital_signs_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vital_signs'))
    )
    op.create_index('ix_vital_signs_patient_time', 'vital_signs', ['patient_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vital_signs_patient_time', table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index(op.f('ix_patient_notes_patient_id'), table_name='patient_notes')
    op.drop_table('patient_notes')
    op.drop_index('ix_lab_results_patient_time', table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_interventions_patient_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_clinical_events_patient_id'), table_name='clinical_events')
    op.drop_table('clinical_events')
    op.drop_index(op.f('ix_round_reports_started_at'), table_name='round_reports')
    op.drop_index(op.f('ix_round_reports_run_id'), table_name='round_reports')
    op.drop_table('round_reports')
    op.drop_index(op.f('ix_patients_run_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_run_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_key'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_action_proposals_status'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_session_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_run_id'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_table('tool_configs')
    op.drop_table('skills')
    op.drop_table('simulation_runs')
    op.drop_table('rules')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
